#!/bin/sh

# $FreeBSD: branches/2021Q1/sysutils/consul/files/consul.in 543983 2020-08-02 17:23:27Z swills $
#
# PROVIDE: consul
# REQUIRE: NETWORKING SERVERS DAEMON
# KEYWORD: shutdown
#
# Add consul_enable="YES" to /etc/rc.conf to enable Consul
#
# Additional variables you can define are:
#
# see rc.subr(8) for additional variables and options
#

. /etc/rc.subr

name=gcs
rcvar=gcs_enable

load_rc_config $name

#: ${consul_enable:="NO"}

start_precmd="gcs_start_precmd"
extra_commands="reload"
pidfile="/var/run/gocdserver.pid"
procname="/root/go-server-21.2.0/bin/go-server"
command="/usr/sbin/daemon"
PATH=${PATH}:/usr/local/bin
export PATH
command_args="-o /root/gcs.log -t ${name} -p ${pidfile} /usr/bin/env /root/go-server-21.2.0/bin/go-server console"

gcs_start_precmd()
{
}

run_rc_command "$1"